#!/bin/sh
mdsConnect andros
mdsOpen $(hostname)
mdsPutCh -v 1 --size=4 --expr "\"Build_Signal(Build_With_Units(\$VALUE, 'raw'),\$,%tbase)\"" --field ".BOLO1.CH%02d" :
mdsClose
mdsDisconnect
/usr/local/bin/reset.dsp
